name: Setup Environment

inputs:
  branch:
    required: true
    type: string
    
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set env variables based on the target environment
      shell: bash
      run: |
        API_NAME=$(grep -oPm1 "(?<=<name>)[^<]+" pom.xml)
        echo "API_NAME=$API_NAME" >> $GITHUB_ENV
        
        if [[ "${{ inputs.branch }}" == "qa" ]]; then
          echo "MULE_ENV=sit" >> $GITHUB_ENV
          echo "TARGET_ID=***" >> $GITHUB_ENV
          echo "ENV_ID=***" >> $GITHUB_ENV
        elif [[ "${{ inputs.branch }}" == "preprod" ]]; then
          echo "MULE_ENV=uat" >> $GITHUB_ENV
          echo "TARGET_ID=***" >> $GITHUB_ENV
          echo "ENV_ID=***" >> $GITHUB_ENV
        elif [[ "${{ inputs.branch }}" == "test" ]]; then
          echo "MULE_ENV=uat" >> $GITHUB_ENV
          echo "TARGET_ID=***" >> $GITHUB_ENV
          echo "ENV_ID=***" >> $GITHUB_ENV
        elif [[ "${{ inputs.branch }}" == "main" ]]; then
          echo "MULE_ENV=prod" >> $GITHUB_ENV
          echo "TARGET_ID=***" >> $GITHUB_ENV
          echo "ENV_ID=***" >> $GITHUB_ENV

        elif [[ "${{ inputs.branch }}" == "sit" ]]; then
          echo "MULE_ENV=sit" >> $GITHUB_ENV
          echo "TARGET_ID=***" >> $GITHUB_ENV
          echo "ENV_ID=***" >> $GITHUB_ENV
        elif [[ "${{ inputs.branch }}" == "uat" ]]; then
          echo "MULE_ENV=uat" >> $GITHUB_ENV
          echo "TARGET_ID=***" >> $GITHUB_ENV
          echo "ENV_ID=***" >> $GITHUB_ENV
          
        else
          # Default : dev env
          echo "MULE_ENV=dev" >> $GITHUB_ENV
          echo "TARGET_ID=***" >> $GITHUB_ENV
          echo "ENV_ID=***" >> $GITHUB_ENV
        fi
        
    - name: Print target nvironment
      shell: bash
      run: |
        echo "The environment set is: ${{ env.MULE_ENV }}"   
