name: Build Maven Package and Upload Jar

inputs:
  branch:
    required: true
    type: string

outputs:
  uploaded_artifact:
    value: ${{ steps.build.outputs.uploaded_artifact }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Maven Package
      shell: bash
      env:
        nexus_username: ${{ env.NEXUS_USERNAME }}
        nexus_password: ${{ env.NEXUS_PASSWORD }}
        jfrog_username: ${{ env.ARTIFACTORY_USERNAME }}
        jfrog_accesstoken: ${{ env.ARTIFACTORY_TOKEN }}  
      run: |
        mvn clean package -DskipMunitTests -Dmule.env=${{env.MULE_ENV}} --settings .maven/settings.xml

    - name: Set up JFrog
      # if: ${{ inputs.branch != 'dev' }}
      uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_URL: ${{ env.JFROG_URL }}
        JF_ACCESS_TOKEN: ${{ env.ARTIFACTORY_TOKEN }}

    - name: Upload JAR to JFrog
      # if: ${{ inputs.branch != 'dev' }}
      id: upload_jar
      env: 
        JFROG_REPO: "o2-075-maven"
        JFROG_ARTIFACTORY_PREFIX: "075"
      shell: bash
      run: |
          latest_jar=$(ls -t target/*.jar | head -n 1)
          
          base_name=$(basename "$latest_jar" .jar) 
          
          git_hash=$(git rev-parse --short HEAD) 
          
          renamed_base=$(echo "$base_name" | sed -E "s/([0-9]+\.[0-9]+\.[0-9]+)/\1-${git_hash}/")
          renamed_jar="target/${renamed_base}.jar" 
          mv "$latest_jar" "$renamed_jar" 
          
          echo "Uploading JAR to Artifactory..." 
          echo "Uploading $renamed_jar to ${{env.JFROG_REPO}}/"
          jf rt u "$renamed_jar" "${{env.JFROG_REPO}}/" 
          echo "uploaded_artifact=$(basename "$renamed_jar")" >> $GITHUB_OUTPUT
  
