name: "Code quality & security checks - by SonarQube (Maven)"
inputs:
  branch:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: SonarQube scan via Maven (force XML/YAML/JSON)
      shell: bash 
      run: |
        mvn org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar \
          -s ./.maven/settings.xml \
          -Dmule.env=${{env.MULE_ENV}} -Dconfig.decoding.key=${{env.decoding_key}} \
          -Dsonar.host.url="${{ env.SONAR_HOST_URL }}" \
          -Dsonar.token="${{ env.SONAR_TOKEN }}" \
          -Dsonar.projectKey="075b-${{ env.API_NAME }}" \
          -Dsonar.projectName="075b-${{ env.API_NAME }}" \
          -Dsonar.projectVersion="${{ env.SONAR_PROJECT_VERSION }}" \
          -Dsonar.sources="src,mule-artifact.json,pom.xml" \
          -Dsonar.inclusions="**/*.xml,**/*.yaml,**/*.yml,**/*.json" \
          -Dsonar.exclusions=".github/**,target/**,.mule/**,**/*.class,**/*.jar,**/*.war,**/*.ear" \
          -Dsonar.sourceEncoding="UTF-8" \
          -Dsonar.scm.exclusions.disabled="true" \
          -Dsonar.xml.file.suffixes=".xml" \
          -Dsonar.json.file.suffixes=".json" \
          -Dsonar.yaml.file.suffixes=".yaml,.yml" \
          -Dsonar.yaml.activate=true \
          -Dsonar.json.activate=true \
          -Dsonar.qualitygate.wait="false" \
          -Dsonar.qualitygate.timeout="600"
      #sonar.qualitygate.wait -> wait for the Quality Gate result and fail the build if the gate fails
