name: Maven Test

runs:
  using: composite

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    # - name: Caching Maven dependencies
    #   uses: actions/cache@v3
    #   with:
    #       path: ~/.m2/repository
    #       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }} 
    #       restore-keys: | 
    #         ${{ runner.os }}-maven-

    - name: Maven Test
      shell: bash
      env:
        nexus_username: ${{ env.NEXUS_USERNAME }}
        nexus_password: ${{ env.NEXUS_PASSWORD }}
        jfrog_username: ${{ env.ARTIFACTORY_USERNAME }}
        jfrog_accesstoken: ${{ env.ARTIFACTORY_TOKEN }} 
        anypoint_username: ${{ env.ANYPOINT_USERNAME }}
        anypoint_password: ${{ env.ANYPOINT_PASSWORD }}
      run: |
        mvn clean test -DskipMunitTests -Dmule.env=${{env.MULE_ENV}} -Dconfig.decoding.key=${{env.decoding_key}} --settings .maven/settings.xml
